### ISSUE TITLE
python -m minihack.scripts.play_gui --env MiniHack-Pray-v0 fails

### ISSUE THREAD

**Issue by manuel-delverme** [facebookresearch/nle#369]
## To Reproduce

// This one works well
python -m minihack.scripts.play_gui --env MiniHack-Eat-v0

// This one fails
python -m minihack.scripts.play_gui --env MiniHack-Pray-v0

## Environment
Collecting environment information...
/home/user/projects/venv3.10/lib/python3.10/site-packages/torch/cuda/__init__.py:88: UserWarning: HIP initialization: Unexpected error from hipGetDeviceCount(). Did you run some cuda functions before calling NumHipDevices() that might have already set an error? Error 101: hipErrorInvalidDevice (Triggered internally at ../c10/hip/HIPFunctions.cpp:110.)
  return torch._C._cuda_getDeviceCount() > 0
NLE version: 0.9.0
PyTorch version: 1.13.1+rocm5.2
Is debug build: No
CUDA used to build PyTorch: None

OS: Ubuntu 22.04.3 LTS
GCC version: (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
CMake version: version 3.28.1

Python version: 3.10
Is CUDA available: No
CUDA runtime version: No CUDA
GPU models and configuration: No CUDA
Nvidia driver version: No CUDA
cuDNN version: No CUDA

Versions of relevant libraries:
[pip3] numpy==1.26.3
[pip3] torch==1.13.1+rocm5.2
[conda] Could not collect

## Additional context
```
Traceback (most recent call last):
  File "/home/user/projects/venv3.10/lib/python3.10/site-packages/matplotlib/cbook/__init__.py", line 287, in process
    func(*args, **kwargs)
  File "/home/user/projects/venv3.10/lib/python3.10/site-packages/minihack/scripts/play_gui.py", line 61, in key_handler
    step(action)
  File "/home/user/projects/venv3.10/lib/python3.10/site-packages/minihack/scripts/play_gui.py", line 37, in step
    obs, reward, done, info = env.step(action)
  File "/home/user/projects/venv3.10/lib/python3.10/site-packages/minihack/base.py", line 398, in step
    return super().step(action)
  File "/home/user/projects/venv3.10/lib/python3.10/site-packages/nle/env/base.py", line 373, in step
    end_status = self._is_episode_end(observation)
  File "/home/user/projects/venv3.10/lib/python3.10/site-packages/minihack/base.py", line 404, in _is_episode_end
    result = self.reward_manager.check_episode_end_call(
  File "/home/user/projects/venv3.10/lib/python3.10/site-packages/minihack/reward_manager.py", line 731, in check_episode_end_call
    reward += event.check(
  File "/home/user/projects/venv3.10/lib/python3.10/site-packages/minihack/reward_manager.py", line 141, in check
    if env._actions[action] == self.action and _standing_on_top(
AttributeError: 'MiniHackPray' object has no attribute '_actions'
```

**Comment by manuel-delverme** [comment]
It seems the issue is `MiniHackPray` expecting _actions to be present but: https://github.com/facebookresearch/nle/issues/273

**Comment by manuel-delverme** [comment]
Wrong repo.. closing
