### ISSUE TITLE
Cannot build dockerfile, PEP 517?

### ISSUE THREAD

**Issue by apsears** [facebookresearch/nle#46]
Cannot build dockerfile, fails at nle wheel building which would not appear to be an issue with my host computer. Below is the output. Any suggestion on resolving this?

```
Sending build context to Docker daemon  135.5MB

Step 1/18 : FROM nvidia/cuda:10.2-cudnn7-devel-ubuntu18.04
 ---> 3ae6814329d3
Step 2/18 : ARG PYTHON_VERSION=3.8
 ---> Using cache
 ---> 2f917637e457
Step 3/18 : ARG DEBIAN_FRONTEND=noninteractive
 ---> Using cache
 ---> d28698b8aee0
Step 4/18 : RUN apt-get update && apt-get install -yq     apt-transport-https     ca-certificates     gnupg     wget     git     software-properties-common     build-essential     emacs     vim     python3-pip
 ---> Using cache
 ---> ca382adaf3e4
Step 5/18 : RUN apt-get update && apt-get install -y     curl     make     g++     clang     bison     flex     libncurses-dev     libzmq3-dev
 ---> Using cache
 ---> f5fa588649c5
Step 6/18 : RUN wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc 2>/dev/null | apt-key add -
 ---> Using cache
 ---> bea5b6b36db9
Step 7/18 : RUN apt-add-repository 'deb https://apt.kitware.com/ubuntu/ bionic main'
 ---> Using cache
 ---> 0fc398f6ac43
Step 8/18 : RUN apt-get update && apt-get --allow-unauthenticated install -yq     cmake     kitware-archive-keyring
 ---> Using cache
 ---> ff486366e566
Step 9/18 : WORKDIR /opt/flatbuffers
 ---> Using cache
 ---> a860577546cc
Step 10/18 : RUN curl -fSL "https://github.com/google/flatbuffers/archive/v1.12.0.tar.gz" -o flatbuffers.tar.gz     && tar xzf flatbuffers.tar.gz     && cd flatbuffers-*     && cmake        -G "Unix Makefiles"        -DCMAKE_BUILD_TYPE=Release     && make     && make install     && cp src/idl_parser.cpp src/idl_gen_text.cpp /usr/local/include/flatbuffers
 ---> Using cache
 ---> 28d98bf1b298
Step 11/18 : WORKDIR /opt/conda_setup
 ---> Using cache
 ---> e924438ae76e
Step 12/18 : RUN curl -o miniconda.sh https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh &&      chmod +x miniconda.sh &&      ./miniconda.sh -b -p /opt/conda &&      /opt/conda/bin/conda install -y python=$PYTHON_VERSION &&      /opt/conda/bin/conda clean -ya
 ---> Using cache
 ---> 5998da5015be
Step 13/18 : ENV PATH /opt/conda/bin:$PATH
 ---> Using cache
 ---> fd8568837916
Step 14/18 : RUN python -m pip install --upgrade pip ipython ipdb
 ---> Using cache
 ---> eba7aac81079
Step 15/18 : WORKDIR /opt/nle
 ---> Using cache
 ---> 64509b2547c6
Step 16/18 : COPY . .
 ---> 33e55777100c
Step 17/18 : RUN pip install ".[all]"
 ---> Running in 8db56f34ded5
Processing /opt/nle
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
Collecting pybind11>=2.2
  Using cached pybind11-2.5.0-py2.py3-none-any.whl (296 kB)
Collecting numpy>=1.16
  Downloading numpy-1.19.0-cp38-cp38-manylinux2010_x86_64.whl (14.6 MB)
Collecting flatbuffers>=1.10
  Downloading flatbuffers-1.12-py2.py3-none-any.whl (15 kB)
Collecting pyzmq>=19.0.0
  Downloading pyzmq-19.0.1-cp38-cp38-manylinux1_x86_64.whl (1.1 MB)
Collecting gym>=0.15
  Downloading gym-0.17.2.tar.gz (1.6 MB)
Collecting flake8>=3.7; extra == "all"
  Downloading flake8-3.8.3-py2.py3-none-any.whl (72 kB)
Collecting torch>=1.3.1; extra == "all"
  Downloading torch-1.5.1-cp38-cp38-manylinux1_x86_64.whl (753.2 MB)
Collecting sphinx>=2.4.4; extra == "all"
  Downloading Sphinx-3.1.1-py3-none-any.whl (2.9 MB)
Collecting black>=19.10b0; extra == "all"
  Downloading black-19.10b0-py36-none-any.whl (97 kB)
Collecting flake8-bugbear>=20.1; extra == "all"
  Downloading flake8_bugbear-20.1.4-py36.py37.py38-none-any.whl (15 kB)
Collecting sphinx-rtd-theme==0.4.3; extra == "all"
  Downloading sphinx_rtd_theme-0.4.3-py2.py3-none-any.whl (6.4 MB)
Collecting pre-commit>=2.0.1; extra == "all"
  Downloading pre_commit-2.6.0-py2.py3-none-any.whl (171 kB)
Collecting cmake-format>=0.6.10; extra == "all"
  Downloading cmake_format-0.6.10-py3-none-any.whl (163 kB)
Collecting pytest>=5.3; extra == "all"
  Downloading pytest-5.4.3-py3-none-any.whl (248 kB)
Collecting scipy
  Downloading scipy-1.5.0-cp38-cp38-manylinux1_x86_64.whl (25.7 MB)
Collecting pyglet<=1.5.0,>=1.4.0
  Downloading pyglet-1.5.0-py2.py3-none-any.whl (1.0 MB)
Collecting cloudpickle<1.4.0,>=1.2.0
  Downloading cloudpickle-1.3.0-py2.py3-none-any.whl (26 kB)
Collecting pyflakes<2.3.0,>=2.2.0
  Downloading pyflakes-2.2.0-py2.py3-none-any.whl (66 kB)
Collecting pycodestyle<2.7.0,>=2.6.0a1
  Downloading pycodestyle-2.6.0-py2.py3-none-any.whl (41 kB)
Collecting mccabe<0.7.0,>=0.6.0
  Downloading mccabe-0.6.1-py2.py3-none-any.whl (8.6 kB)
Collecting future
  Downloading future-0.18.2.tar.gz (829 kB)
Collecting sphinxcontrib-applehelp
  Downloading sphinxcontrib_applehelp-1.0.2-py2.py3-none-any.whl (121 kB)
Collecting docutils>=0.12
  Downloading docutils-0.16-py2.py3-none-any.whl (548 kB)
Requirement already satisfied: setuptools in /opt/conda/lib/python3.8/site-packages (from sphinx>=2.4.4; extra == "all"->nle==0.1.2+a5a7207) (47.3.1.post20200622)
Collecting snowballstemmer>=1.1
  Downloading snowballstemmer-2.0.0-py2.py3-none-any.whl (97 kB)
Collecting sphinxcontrib-serializinghtml
  Downloading sphinxcontrib_serializinghtml-1.1.4-py2.py3-none-any.whl (89 kB)
Collecting Jinja2>=2.3
  Downloading Jinja2-2.11.2-py2.py3-none-any.whl (125 kB)
Collecting sphinxcontrib-htmlhelp
  Downloading sphinxcontrib_htmlhelp-1.0.3-py2.py3-none-any.whl (96 kB)
Collecting sphinxcontrib-qthelp
  Downloading sphinxcontrib_qthelp-1.0.3-py2.py3-none-any.whl (90 kB)
Requirement already satisfied: Pygments>=2.0 in /opt/conda/lib/python3.8/site-packages (from sphinx>=2.4.4; extra == "all"->nle==0.1.2+a5a7207) (2.6.1)
Collecting babel>=1.3
  Downloading Babel-2.8.0-py2.py3-none-any.whl (8.6 MB)
Collecting imagesize
  Downloading imagesize-1.2.0-py2.py3-none-any.whl (4.8 kB)
Collecting alabaster<0.8,>=0.7
  Downloading alabaster-0.7.12-py2.py3-none-any.whl (14 kB)
Collecting sphinxcontrib-devhelp
  Downloading sphinxcontrib_devhelp-1.0.2-py2.py3-none-any.whl (84 kB)
Collecting packaging
  Downloading packaging-20.4-py2.py3-none-any.whl (37 kB)
Requirement already satisfied: requests>=2.5.0 in /opt/conda/lib/python3.8/site-packages (from sphinx>=2.4.4; extra == "all"->nle==0.1.2+a5a7207) (2.24.0)
Collecting sphinxcontrib-jsmath
  Downloading sphinxcontrib_jsmath-1.0.1-py2.py3-none-any.whl (5.1 kB)
Collecting attrs>=18.1.0
  Downloading attrs-19.3.0-py2.py3-none-any.whl (39 kB)
Collecting regex
  Downloading regex-2020.6.8-cp38-cp38-manylinux2010_x86_64.whl (673 kB)
Collecting pathspec<1,>=0.6
  Downloading pathspec-0.8.0-py2.py3-none-any.whl (28 kB)
Collecting toml>=0.9.4
  Downloading toml-0.10.1-py2.py3-none-any.whl (19 kB)
Collecting click>=6.5
  Downloading click-7.1.2-py2.py3-none-any.whl (82 kB)
Collecting typed-ast>=1.4.0
  Downloading typed_ast-1.4.1-cp38-cp38-manylinux1_x86_64.whl (768 kB)
Collecting appdirs
  Downloading appdirs-1.4.4-py2.py3-none-any.whl (9.6 kB)
Collecting virtualenv>=20.0.8
  Downloading virtualenv-20.0.25-py2.py3-none-any.whl (4.7 MB)
Collecting pyyaml>=5.1
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
Collecting identify>=1.0.0
  Downloading identify-1.4.21-py2.py3-none-any.whl (97 kB)
Collecting nodeenv>=0.11.1
  Downloading nodeenv-1.4.0-py2.py3-none-any.whl (21 kB)
Collecting cfgv>=2.0.0
  Downloading cfgv-3.1.0-py2.py3-none-any.whl (7.3 kB)
Requirement already satisfied: six>=1.13.0 in /opt/conda/lib/python3.8/site-packages (from cmake-format>=0.6.10; extra == "all"->nle==0.1.2+a5a7207) (1.15.0)
Collecting py>=1.5.0
  Downloading py-1.9.0-py2.py3-none-any.whl (99 kB)
Collecting more-itertools>=4.0.0
  Downloading more_itertools-8.4.0-py3-none-any.whl (43 kB)
Requirement already satisfied: wcwidth in /opt/conda/lib/python3.8/site-packages (from pytest>=5.3; extra == "all"->nle==0.1.2+a5a7207) (0.2.5)
Collecting pluggy<1.0,>=0.12
  Downloading pluggy-0.13.1-py2.py3-none-any.whl (18 kB)
Collecting MarkupSafe>=0.23
  Downloading MarkupSafe-1.1.1-cp38-cp38-manylinux1_x86_64.whl (32 kB)
Collecting pytz>=2015.7
  Downloading pytz-2020.1-py2.py3-none-any.whl (510 kB)
Collecting pyparsing>=2.0.2
  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)
Requirement already satisfied: chardet<4,>=3.0.2 in /opt/conda/lib/python3.8/site-packages (from requests>=2.5.0->sphinx>=2.4.4; extra == "all"->nle==0.1.2+a5a7207) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /opt/conda/lib/python3.8/site-packages (from requests>=2.5.0->sphinx>=2.4.4; extra == "all"->nle==0.1.2+a5a7207) (2.9)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /opt/conda/lib/python3.8/site-packages (from requests>=2.5.0->sphinx>=2.4.4; extra == "all"->nle==0.1.2+a5a7207) (1.25.9)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.8/site-packages (from requests>=2.5.0->sphinx>=2.4.4; extra == "all"->nle==0.1.2+a5a7207) (2020.6.20)
Collecting distlib<1,>=0.3.0
  Downloading distlib-0.3.1-py2.py3-none-any.whl (335 kB)
Collecting filelock<4,>=3.0.0
  Downloading filelock-3.0.12-py3-none-any.whl (7.6 kB)
Building wheels for collected packages: nle, gym, future, pyyaml
  Building wheel for nle (PEP 517): started
  Building wheel for nle (PEP 517): finished with status 'error'
[91m  ERROR: Command errored out with exit status 1:
   command: /opt/conda/bin/python /opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpbd45tgrn
       cwd: /tmp/pip-req-build-dyl8chyj
  Complete output (118 lines):
  Building wheel nle-0.1.2+a5a7207
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.8
  creating build/lib.linux-x86_64-3.8/nle
  copying nle/version.py -> build/lib.linux-x86_64-3.8/nle
  copying nle/__init__.py -> build/lib.linux-x86_64-3.8/nle
  creating build/lib.linux-x86_64-3.8/nle/env
  copying nle/env/tasks.py -> build/lib.linux-x86_64-3.8/nle/env
  copying nle/env/base.py -> build/lib.linux-x86_64-3.8/nle/env
  copying nle/env/__init__.py -> build/lib.linux-x86_64-3.8/nle/env
  creating build/lib.linux-x86_64-3.8/nle/nethack
  copying nle/nethack/actions.py -> build/lib.linux-x86_64-3.8/nle/nethack
  copying nle/nethack/nethack.py -> build/lib.linux-x86_64-3.8/nle/nethack
  copying nle/nethack/print_message.py -> build/lib.linux-x86_64-3.8/nle/nethack
  copying nle/nethack/__init__.py -> build/lib.linux-x86_64-3.8/nle/nethack
  copying nle/nethack/ptyprocess.py -> build/lib.linux-x86_64-3.8/nle/nethack
  creating build/lib.linux-x86_64-3.8/nle/agent
  copying nle/agent/agent.py -> build/lib.linux-x86_64-3.8/nle/agent
  copying nle/agent/vtrace.py -> build/lib.linux-x86_64-3.8/nle/agent
  copying nle/agent/__init__.py -> build/lib.linux-x86_64-3.8/nle/agent
  creating build/lib.linux-x86_64-3.8/nle/scripts
  copying nle/scripts/ttyplay.py -> build/lib.linux-x86_64-3.8/nle/scripts
  copying nle/scripts/ttyrec.py -> build/lib.linux-x86_64-3.8/nle/scripts
  copying nle/scripts/collect_env.py -> build/lib.linux-x86_64-3.8/nle/scripts
  copying nle/scripts/play.py -> build/lib.linux-x86_64-3.8/nle/scripts
  copying nle/scripts/plot.py -> build/lib.linux-x86_64-3.8/nle/scripts
  copying nle/scripts/test_raw_nethack.py -> build/lib.linux-x86_64-3.8/nle/scripts
  copying nle/scripts/__init__.py -> build/lib.linux-x86_64-3.8/nle/scripts
  copying nle/scripts/check_nethack_speed.py -> build/lib.linux-x86_64-3.8/nle/scripts
  package init file 'nle/tests/__init__.py' not found (or not a regular file)
  creating build/lib.linux-x86_64-3.8/nle/tests
  copying nle/tests/test_ptyprocess.py -> build/lib.linux-x86_64-3.8/nle/tests
  copying nle/tests/test_forking.py -> build/lib.linux-x86_64-3.8/nle/tests
  copying nle/tests/test_memory.py -> build/lib.linux-x86_64-3.8/nle/tests
  copying nle/tests/test_nethack.py -> build/lib.linux-x86_64-3.8/nle/tests
  copying nle/tests/test_envs.py -> build/lib.linux-x86_64-3.8/nle/tests
  running build_ext
  -- The C compiler identification is GNU 7.5.0
  -- The CXX compiler identification is GNU 7.5.0
  -- Check for working C compiler: /usr/bin/cc
  -- Check for working C compiler: /usr/bin/cc - works
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Check for working CXX compiler: /usr/bin/c++
  -- Check for working CXX compiler: /usr/bin/c++ - works
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Building nle backend version: 0.1.2
  -- HACKDIR set to: /opt/conda/nethackdir
  -- ZMQ include: /usr/include
  -- ZMQ libs: /usr/lib/x86_64-linux-gnu/libzmq.so
  -- Flatbuffers include: /usr/local/include
  -- Flatbuffers libs: /usr/local/lib/libflatbuffers.a
  CMake Error at win/rl/CMakeLists.txt:31 (add_subdirectory):
    The source directory
  
      /tmp/pip-req-build-dyl8chyj/third_party/pybind11
  
    does not contain a CMakeLists.txt file.
  
  
  CMake Error at win/rl/CMakeLists.txt:33 (pybind11_add_module):
    Unknown CMake command "pybind11_add_module".
  
  
  -- Configuring incomplete, errors occurred!
  See also "/tmp/pip-req-build-dyl8chyj/build/temp.linux-x86_64-3.8/CMakeFiles/CMakeOutput.log".
  Traceback (most recent call last):
    File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/opt/conda/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-2pccjznw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 211, in build_wheel
      return self._build_with_temp_dir(['bdist_wheel'], '.whl',
    File "/tmp/pip-build-env-2pccjznw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 197, in _build_with_temp_dir
      self.run_setup()
    File "/tmp/pip-build-env-2pccjznw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 248, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-2pccjznw/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 115, in <module>
      setuptools.setup(
    File "/tmp/pip-build-env-2pccjznw/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 165, in setup
      return distutils.core.setup(**attrs)
    File "/opt/conda/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/opt/conda/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-build-env-2pccjznw/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 223, in run
      self.run_command('build')
    File "/opt/conda/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/opt/conda/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/opt/conda/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/opt/conda/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "setup.py", line 25, in run
      self.build_extension(ext)
    File "setup.py", line 46, in build_extension
      subprocess.check_call(cmake_cmd, cwd=self.build_temp)
    File "/opt/conda/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', PosixPath('/tmp/pip-req-build-dyl8chyj'), '-DPYTHON_SRC_PARENT=/tmp/pip-req-build-dyl8chyj/build/lib.linux-x86_64-3.8', '-DPYTHON_EXECUTABLE=/opt/conda/bin/python', '-DCMAKE_INSTALL_PREFIX=/opt/conda', '-DHACKDIR=/opt/conda/nethackdir']' returned non-zero exit status 1.
  ----------------------------------------
[0m[91m  ERROR: Failed building wheel for nle
[0m  Building wheel for gym (setup.py): started
  Building wheel for gym (setup.py): finished with status 'done'
  Created wheel for gym: filename=gym-0.17.2-py3-none-any.whl size=1650891 sha256=249b65788a76081203af31f2bde84d50d242cdba887586ea128b0c03024109b3
  Stored in directory: /root/.cache/pip/wheels/48/bf/7c/44b1b8e4ad998fc48e31caedbb9e028351861b8d20632642bc
  Building wheel for future (setup.py): started
  Building wheel for future (setup.py): finished with status 'done'
  Created wheel for future: filename=future-0.18.2-py3-none-any.whl size=491058 sha256=e32b0d60bfa40832fe798821b477be6a1e14976555bf99b301ab9b75d1845c13
  Stored in directory: /root/.cache/pip/wheels/8e/70/28/3d6ccd6e315f65f245da085482a2e1c7d14b90b30f239e2cf4
  Building wheel for pyyaml (setup.py): started
  Building wheel for pyyaml (setup.py): finished with status 'done'
  Created wheel for pyyaml: filename=PyYAML-5.3.1-cp38-cp38-linux_x86_64.whl size=44617 sha256=a9375843a77f1fd71459bf73b1aefba505173bdb7205ef37568b7c621b8b8337
  Stored in directory: /root/.cache/pip/wheels/13/90/db/290ab3a34f2ef0b5a0f89235dc2d40fea83e77de84ed2dc05c
Successfully built gym future pyyaml
Failed to build nle
[91mERROR: Could not build wheels for nle which use PEP 517 and cannot be installed directly
[0m
```

EDIT(NN): formatting.

**Comment by edran** [comment]
You don't seem to have cloned the submodules. Can you do `git submodule update --init --recursive` and then try again, please?

That said, you shouldn't be using the master branch unless really necessary. A built image is available with `docker pull fairnle/nle:stable`, which pulls the latest release on a cuda-compatible Ubuntu 18.04 image.

**Comment by apsears** [comment]
Thank you, yes, 

git submodule update --init --recursive 

must have been the missing step
