### ISSUE TITLE
Cannot import nle, python 3.8.3

### ISSUE THREAD

**Issue by apsears** [facebookresearch/nle#47]
Mac OS Catalina, nethack installed using homebrew. Cannot import nle after installing with pip.  Would welcome suggestions on how I might be misconfigured!

Python 3.8.3 (default, Jun 26 2020, 08:39:17) 
[Clang 11.0.3 (clang-1103.0.32.59)] on darwin

```
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> import nle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/nle/__init__.py", line 4, in <module>
    import nle.env
  File "/usr/local/lib/python3.8/site-packages/nle/env/__init__.py", line 4, in <module>
    from nle.env.base import NLE, DUNGEON_SHAPE, seed_list_to_dict
  File "/usr/local/lib/python3.8/site-packages/nle/env/base.py", line 16, in <module>
    from nle import nethack
  File "/usr/local/lib/python3.8/site-packages/nle/nethack/__init__.py", line 3, in <module>
    from nle.nethack.nethack import NetHack, SEED_KEYS
  File "/usr/local/lib/python3.8/site-packages/nle/nethack/nethack.py", line 57, in <module>
    line = f.readline()
  File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xcf in position 0: invalid continuation byte
>>> 

pip3.8 install nle
Requirement already satisfied: nle in /usr/local/lib/python3.8/site-packages (0.1.2)
Requirement already satisfied: pyzmq>=19.0.0 in /usr/local/lib/python3.8/site-packages (from nle) (19.0.0)
Requirement already satisfied: gym>=0.15 in /usr/local/lib/python3.8/site-packages (from nle) (0.17.2)
Requirement already satisfied: pybind11>=2.2 in /usr/local/lib/python3.8/site-packages (from nle) (2.5.0)
Requirement already satisfied: numpy>=1.16 in /usr/local/lib/python3.8/site-packages (from nle) (1.18.3)
Requirement already satisfied: flatbuffers>=1.10 in /usr/local/lib/python3.8/site-packages (from nle) (1.12)
Requirement already satisfied: cloudpickle<1.4.0,>=1.2.0 in /usr/local/lib/python3.8/site-packages (from gym>=0.15->nle) (1.3.0)
Requirement already satisfied: pyglet<=1.5.0,>=1.4.0 in /usr/local/lib/python3.8/site-packages (from gym>=0.15->nle) (1.5.0)
Requirement already satisfied: scipy in /usr/local/lib/python3.8/site-packages (from gym>=0.15->nle) (1.4.1)
Requirement already satisfied: future in /usr/local/lib/python3.8/site-packages (from pyglet<=1.5.0,>=1.4.0->gym>=0.15->nle) (0.18.2)
```

EDIT(NN): formatting.

**Comment by edran** [comment]
Hi Adam,

The `nle` package builds its own version of nethack, and it is not compatible with the homebrew binary (or any version of NetHack outside of the one that we ship, at least for the time being). To build our version of `nethack`, do -- preferably in a conda / venv environment -- `pip install nle`, or `pip install .` if you are using the cloned repo.

I would also advise to not clone the repo, and simply install the package from PyPI, as it will pull the latest released version (rather than the master branch, which we use for development).
