### ISSUE TITLE
Ability to load NetHack via gym API into Deepmind Acme or Berkeley BAIR rlpyt RL frameworks

### ISSUE THREAD

**Issue by MauriceManning** [facebookresearch/nle#49]
## 🚀 Feature
RL learning frameworks such as Deepmind Acme, Google Dopamine or Berkeley BAIR rlpyt enable users to experiment with multiple RL algorithms on Atari or OpenAI gym environments. 

## Motivation
NetHack should be included as it provides an efficient yet challenging environment on which to experiment.
It would be great to be able to load NetHack NLE into these frameworks but currently not possible.

## Pitch
For both Acme and rlpyt I installed the framework into an Ubuntu 18.04 docker container then installed NLE in that same container. I verified that the framework was able to run its provided examples and that NLE sample scripts also worked before modifying one of the framework examples to use the NetHack-v0  gym environment. 

Berkeley BAIR rlpyt:
Ran examples/example_2.py with environment set to 'NetHack-v0', when the agent samples the space it first checks that env_spaces.action.shape == 1 and fails. There are a number of attributes in the action and observation space that are not defined which rlpyt expects to be available. 

DeepMind Acme:
Modified examples/gym/run_d4pg.py to use NetHack-v0 but recieved data type mismatch errors in the initialization of the D4PG agent. 
    # Get observation and action specs.
    act_spec = environment_spec.actions
    obs_spec = environment_spec.observations
    emb_spec = tf2_utils.create_variables(observation_network, [obs_spec])

Have not yet tried Dopamine but expect similar with the action and observation spaces with the discrete space from NLE.

**Comment by heiner** [comment]
Hey Maurice,

Thanks for your interest.

This sounds like we are not setting all spec attributes correctly. We'll look into this.

**Comment by heiner** [comment]
Hey MauriceManning, is this still an issue?

**Comment by MauriceManning** [comment]
Hello. Yes, have reproduced with rlpyt using the current nle codebase. To provide some context:
- I am installing the nle, then installing the current rlpyt into that same conda environment.
- this produces two separate gym envs  so I edit ./lib/python3.8/site-packages/nle/env/__init__.py and add
from nle.env.base import NLE, DUNGEON_SHAPE
so that the NetHack-v0 env can be located by rlpyt.
- then I modify one of the rlpyt examples rlpyt/examples/example2.py to run with the NetHack-v0 env
parser.add_argument('--env_id', help='environment ID', default='NetHackScore-v0')

I realize this is a little hacky but I am just trying to get any of the provided algorithms to load and run a basic NetHack space. If this is the wrong route to connect the two (rlpyt and nle) please let me know.

the current error is the same as before: 
/Users/mmanning/anaconda3/envs/nle/bin/python /Users/mmanning/Dev/rl/rlpytnle/rlpyt/examples/example_2.py
Unable to import tensorboard SummaryWriter, proceeding without.
logger_context received log_dir outside of /Users/mmanning/Dev/rl/rlpyt/data: prepending by /Users/mmanning/Dev/rl/rlpyt/data/local/<yyyymmdd>/<hhmmss>/
2020-11-21 12:04:11.886631  | sac_NetHackScore-v0_0 Runner  master CPU affinity: UNAVAILABLE MacOS.
2020-11-21 12:04:11.886720  | sac_NetHackScore-v0_0 Runner  master Torch threads: 1.
using seed 8086
Traceback (most recent call last):
  File "/Users/mmanning/Dev/rl/rlpytnle/rlpyt/examples/example_2.py", line 57, in <module>
    build_and_train(
  File "/Users/mmanning/Dev/rl/rlpytnle/rlpyt/examples/example_2.py", line 47, in build_and_train
    runner.train()
  File "/Users/mmanning/Dev/rl/rlpyt/rlpyt/runners/minibatch_rl.py", line 301, in train
    n_itr = self.startup()
  File "/Users/mmanning/Dev/rl/rlpyt/rlpyt/runners/minibatch_rl.py", line 74, in startup
    examples = self.sampler.initialize(
  File "/Users/mmanning/Dev/rl/rlpyt/rlpyt/samplers/serial/sampler.py", line 50, in initialize
    agent.initialize(envs[0].spaces, share_memory=False,
  File "/Users/mmanning/Dev/rl/rlpyt/rlpyt/agents/qpg/sac_agent.py", line 55, in initialize
    super().initialize(env_spaces, share_memory,
  File "/Users/mmanning/Dev/rl/rlpyt/rlpyt/agents/base.py", line 82, in initialize
    self.env_model_kwargs = self.make_env_to_model_kwargs(env_spaces)
  File "/Users/mmanning/Dev/rl/rlpyt/rlpyt/agents/qpg/sac_agent.py", line 101, in make_env_to_model_kwargs
    assert len(env_spaces.action.shape) == 1
AssertionError

Process finished with exit code 1

I will also try again with DeepMind Acme in the next couple days. thanks for your assistance. May I ask if there are other RL frameworks that your team have used with NLE?

**Comment by MauriceManning** [comment]
Hello
I also reproduced the error with Deepmind Acme. I used the fairnle/nle:stable nle docker container, inside that container I installed Acme using these instructions: https://github.com/deepmind/acme#installation

Then I copied the examples/gym/run_d4pg.py example into the container, added the gym and nle import and used the NetHack-v0 environment in place of MountainCarContinuous-v0. I recieved this type mismatch which is the same issue as I ran into previously with Acme.


root@4deea15bc74f:/opt/acme# python ./run_d4pg.py 
2020-11-23 01:59:06.463040: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-11-23 01:59:06.463107: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
I1123 01:59:09.143711 140349876913984 base.py:165] Created savedir: /opt/acme/nle_data/20201123-015909_kl1qo32y
2020-11-23 01:59:09.172180: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/nvidia/lib:/usr/local/nvidia/lib64
2020-11-23 01:59:09.173271: W tensorflow/stream_executor/cuda/cuda_driver.cc:312] failed call to cuInit: UNKNOWN ERROR (303)
2020-11-23 01:59:09.174008: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (4deea15bc74f): /proc/driver/nvidia/version does not exist
2020-11-23 01:59:09.175436: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN)to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2020-11-23 01:59:09.188455: I tensorflow/core/platform/profile_utils/cpu_utils.cc:104] CPU Frequency: 2904000000 Hz
2020-11-23 01:59:09.189102: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x564ed899deb0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-11-23 01:59:09.189157: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[reverb/cc/platform/tfrecord_checkpointer.cc:143] Initializing TFRecordCheckpointer in /tmp/tmpy2tr1no_
[reverb/cc/platform/tfrecord_checkpointer.cc:322] Loading latest checkpoint from /tmp/tmpy2tr1no_
[reverb/cc/platform/default/server.cc:55] Started replay server on port 24693
WARNING:tensorflow:Entity <function _yield_value at 0x7fa5b78ee820> appears to be a generator function. It will not be converted by AutoGraph.
W1123 01:59:12.369593 140349876913984 ag_logging.py:146] Entity <function _yield_value at 0x7fa5b78ee820> appears to be a generator function. It will not be converted by AutoGraph.
Traceback (most recent call last):
  File "./run_d4pg.py", line 140, in <module>
    app.run(main)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/opt/conda/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "./run_d4pg.py", line 112, in main
    agent = d4pg.D4PG(
  File "/opt/conda/lib/python3.8/site-packages/acme/agents/tf/d4pg/agent.py", line 131, in __init__
    emb_spec = tf2_utils.create_variables(observation_network, [obs_spec])
  File "/opt/conda/lib/python3.8/site-packages/acme/tf/utils.py", line 103, in create_variables
    dummy_output = network(*add_batch_dim(dummy_input))
  File "/opt/conda/lib/python3.8/site-packages/sonnet/src/utils.py", line 89, in _decorate_unbound_method
    return decorator_fn(bound_method, self, args, kwargs)
  File "/opt/conda/lib/python3.8/site-packages/sonnet/src/base.py", line 272, in wrap_with_name_scope
    return method(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/acme/tf/utils.py", line 144, in __call__
    return self._transformation(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/acme/tf/utils.py", line 54, in batch_concat
    return tf.concat(tree.flatten(flat_leaves), axis=-1)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/array_ops.py", line 1654, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1207, in concat_v2
    _ops.raise_from_not_ok_status(e, name)
  File "/opt/conda/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 6843, in raise_from_not_ok_status
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError: cannot compute ConcatV2 as input #1(zero-based) was expected to be a int32 tensor but is a uint8 tensor [Op:ConcatV2] name: concat

**Comment by heiner** [comment]
Hey,

This sounds like NLE produces a uint8 tensor where Acme expects an int32 tensor. I'm fairly certain our gym environment sets the right kind of tensor attributes. Perhaps you want to take this issue up with the Acme team?

**Comment by MauriceManning** [comment]
Ok, I will check with the Acme team for that issue. Any chance that someone from your team can attempt to load into either Berkeley rlpyt or Google Dopamine? Is there a similar framework that works well with NLE?

**Comment by edran** [comment]
Hey @MauriceManning, I can't quite reproduce the issue locally with a minimal example (this one uses dqn + jax, but in the dm_env spec is the same):

```python
from absl import app
from absl import flags

import acme
from acme import wrappers
from acme import specs

from acme.agents.jax import dqn

import haiku as hk
import jax.numpy as jnp

import gym
import nle

def main(_):
    raw_env = gym.make("NetHackScore-v0")
    env = wrappers.GymWrapper(raw_env)
    env = wrappers.SinglePrecisionWrapper(env)

    env_spec = specs.make_environment_spec(env)

    def module(x):
        x = jnp.float32(x['chars'])
        mlp = hk.Sequential([
            hk.Flatten(),
            hk.nets.MLP([50, 50, 23])
        ])
        return mlp(x)

    network = hk.without_apply_rng(hk.transform(module, apply_rng=True))
    agent = dqn.DQN(environment_spec=env_spec, network=network)

    loop = acme.EnvironmentLoop(env, agent)
    loop.run(num_episodes=10)

if __name__ == "__main__":
    app.run(main)
```

I'll give a stab at modifying `d4pg` later, but it would really be helpful if you could copy your code here.

**Comment by MauriceManning** [comment]
Hello @edran 
Very much appreciate your help. May I ask how you went about installing NLE and Acme? I have usually been more successful with starting with the NLE container then installing Acme in the container, but this seems a bit backward.

As for my code, in both Acme and Rlpyt, Ive just used one of their example programs and switched in the NeHack-vo gym env. In the Acme case it is this code:
https://github.com/deepmind/acme/blob/master/examples/gym/run_d4pg.py
but they have recently changed this example and put environment creation in a helper class.

Currently running into an issue with the updates to both Amce and NLE when I attempt to get started with your example where it imports dqn:
Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    from acme.agents.jax import dqn
    ....
  File "/opt/conda/lib/python3.8/site-packages/reverb/pybind.py", line 1, in <module>
    import tensorflow as _tf; from .libpybind import *; del _tf
ImportError: /opt/conda/lib/python3.8/site-packages/reverb/libschema_cc_proto.so: undefined symbol: _ZN6google8protobuf8internal26fixed_address_empty_stringE

which is why I asked about how you installed these two frameworks in a way that makes them both happy. WIll work ona
Again, really appreciate that you took the time to look into this.
Maurice

**Comment by heiner** [comment]
Closing for now, please reopen if this is still relevant.
